[conf]
default-lang = "en"

[lang.en]
thesis = "Master's Thesis"
supervisor = "Supervisor"
performed-in-year = "Performed in the school year"
submission-note = "Submission note"
approved = "Approved"

declaration-title = "Statutory declaration"
declaration-text= "I herewith declare that I have composed the present thesis myself and without use of any other than the cited sources and aids. Sentences or parts of sentences quoted literally are marked as such; other references with regard to the statement and scope are indicated by full details of the publications concerned. The thesis in the same or similar form has not been submitted to any examination body and has not been published. This thesis was not yet, even in part, used in another examination or as a course performance. Furthermore I declare that the submitted written (bound) copies of the present thesis and the version submitted on a data carrier are consistent with each other in contents."

location-date = "Location, Date"

chapter = "Chapter"
section = "Section"
abstract = "Abstract"

figure = "Figure"
table = "Table"
listing = "Listing"

contents = "Contents"
bibliography = "Bibliography"
list-of-figures = "List of Figures"
list-of-tables = "List of Tables"
list-of-listings = "List of Listings"
glossary = "Glossary"

[lang.de]
thesis = "Masterarbeit"
supervisor = "Betreuer"
performed-in-year = "Ausgeführt im Schuljahr"
submission-note = "Abgabevermerk"
approved = "Übernommen von"

declaration-title = "Eidesstattliche Erklärung"
declaration-text = "Ich versichere, dass ich die Arbeit selbständig und ohne fremde Hilfe angefertigt habe. Ich habe keine anderen als die im Literatur- bzw. Quellenverzeichnis angegebenen Hilfsmittel benutzt und mich keiner darüberhinausgehender Internetquellen bedient. Alle Stellen, die wörtlich oder sinngemäß aus Veröffentlichungen entnommen wurden, sind als solche kenntlich gemacht. Ich habe die Arbeit zuvor nicht in einem anderen Prüfungsverfahren eingereicht. Die eingereichte schriftliche Fassung entspricht jener auf dem beiliegenden elektronischen Speichermedium."

location-date = "Ort, Datum"

chapter = "Kapitel"
section = "Abschnitt"
abstract = "Zusammenfassung"

figure = "Abbildung"
table = "Tabelle"
listing = "Auflistung"

contents = "Inhaltsverzeichnis"
bibliography = "Literaturverzeichnis"
list-of-figures = "Abbildungsverzeichnis"
list-of-tables = "Tabellenverzeichnis"
list-of-listings = "Auflistungsverzeichnis"
glossary = "Glossar"
